# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_remove_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
