# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_current_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesquare',
            name='col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamesquare',
            name='row',
            field=models.IntegerField(),
        ),
    ]
